---
- name: "BLOCK >> Log changes to disk"
  block:
    # Based on the LOG_PATH variable, create the per-run log directory
    - name: "LOG >> Build logging directory"
      listen: "updates exist"
      file:
        path: "{{ LOG_PATH }}"
        state: directory
      changed_when: false

    # Next, the updates are templated through the 'natlog' template for
    # longer term storage and reference for troubleshooting.
    - name: "LOG >> Print updates written to device to log file"
      listen: "updates exist"
      template:
        src: "templates/natlog.j2"
        dest: "{{ LOG_PATH }}{{ inventory_hostname }}.txt"
        newline_sequence: '\r\n'

  delegate_to: localhost
...
